### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jithin-j** [jithin-j/TheOriginalsFanWebsite#1]
- Update the readme with the new deployed link (https://jithin-j.github.io/TheOriginalsFanWebsite/)

**Comment by georgioupanayiotis** [comment]
@jithin-j  can you please assign this to me?

**Comment by georgioupanayiotis** [comment]
@jithin-j can i have this issue assigned on me please ?

**Comment by jithin-j** [comment]
> @jithin-j can i have this issue assigned on me please ?

Sure

**Comment by georgioupanayiotis** [comment]
PR created https://github.com/jithin-j/TheOriginalsFanWebsite/pull/4

@jithin-j  it would be very helpful if you can please review it as soon as possible and merge it or label it as "hacktoberfest-accepted"

**Comment by NazimFilzer** [comment]
is this still open?

**Comment by georgioupanayiotis** [comment]
@NazimFilzer  Nope submitted the PR already!

**Comment by jithin-j** [comment]
Merged! Thank you for the contribution..
