### ISSUE TITLE
Edit Footer

### ISSUE THREAD

**Issue by jithin-j** [jithin-j/TheOriginalsFanWebsite#2]
- Edit the footer and add relevant content

**Comment by Aragorn-64** [comment]
Hi @jithin-j , I'd would like to work on this. Can you describe what you want in the footer?

**Comment by Yh010** [comment]
I would like to work on this issue. Could u pls assign this issue? also, what changes do you specifically want?

**Comment by Sushie611** [comment]
could you please assign me the issue

**Comment by Munnachienyi** [comment]
hey, i can add relevant content to make the footer appealing. could you assign me this issue?

**Comment by jithin-j** [comment]
> Hi @jithin-j , I'd would like to work on this. Can you describe what you want in the footer?

The footer section contains irrelevant links such as 'Shop merch' and 'user'. Remove them and also add links to different seasons similar to the ones given in the navbar.

**Comment by jithin-j** [comment]
Will accept the first pull request. Ty for the efforts!

**Comment by Munnachienyi** [comment]
i get what you want me to do, when do you need me to be done?

**Comment by jithin-j** [comment]
This issue is resolved! Thanks for the contribution.
