### ISSUE TITLE
Make the episodes page of all 5 seasons mobile responsive

### ISSUE THREAD

**Issue by jithin-j** [jithin-j/TheOriginalsFanWebsite#6]

**Comment by alvinokafor** [comment]
Hi @jithin-j, I would love to take up this issue.

**Comment by Cheeh1** [comment]
Hi @jithin-j , i would be glad if this issue is assigned to me.. Thanks in anticipation

**Comment by jithin-j** [comment]
Hey guys I'm assigning seasons 1,2 and 3 to @alvinokafor and seasons 4&5 to @Cheeh1

**Comment by jithin-j** [comment]
Hey guys thank you for the contributions. While I have merged both of your pull requests a few changes are required to make seasons 1,2 and 3 look better in mobile view. I really liked @Cheeh1 work, so can you work your magic on the first 3 seasons as well?

**Comment by Cheeh1** [comment]
Okay..i will do just that
Sorry i saw this late. @jithin-j

**Comment by jithin-j** [comment]
@Cheeh1 No worries. Thank you for your contribution!! Closing this issue now..
